/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import formulario.Questionario;

/**
 *
 * @author lucas
 */
public class Principal extends javax.swing.JFrame
{
    Questionario q;
    

    /**
     * Creates new form Principal
     */
    public Principal()
    {
        this.q = new Questionario();
        initComponents();
    }

    public void enviaTitulo(String nome)
    {
        System.out.println(nome);
//        q.setTitulo("qwerty");
        q.setTitulo(nome);
    }
              
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuNovoQuestionario = new javax.swing.JMenuItem();
        jMenuVisualizarQuestionario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jMenu.setText("Menu");

        jMenuNovoQuestionario.setText("Novo Questionário");
        jMenuNovoQuestionario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuNovoQuestionarioActionPerformed(evt);
            }
        });
        jMenu.add(jMenuNovoQuestionario);

        jMenuVisualizarQuestionario.setText("Visualizar Questionário");
        jMenuVisualizarQuestionario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuVisualizarQuestionarioActionPerformed(evt);
            }
        });
        jMenu.add(jMenuVisualizarQuestionario);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNovoQuestionarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuNovoQuestionarioActionPerformed
    {//GEN-HEADEREND:event_jMenuNovoQuestionarioActionPerformed
        jifTituloDescricao obj = new jifTituloDescricao();
        jdpPrincipal.add(obj);
        q.setTitulo(obj.getTitulo());
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuNovoQuestionarioActionPerformed

    private void jMenuVisualizarQuestionarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuVisualizarQuestionarioActionPerformed
    {//GEN-HEADEREND:event_jMenuVisualizarQuestionarioActionPerformed
        jifQuestionarioFinal obj = new jifQuestionarioFinal();
        jdpPrincipal.add(obj);
        obj.recebeTitulo(q.getTitulo());
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuVisualizarQuestionarioActionPerformed
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuNovoQuestionario;
    private javax.swing.JMenuItem jMenuVisualizarQuestionario;
    private javax.swing.JDesktopPane jdpPrincipal;
    // End of variables declaration//GEN-END:variables
}
