/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geradordeformulario;

import formulario.Lista;
import formulario.Questionario;

/**
 *
 * @author lucas
 */
public class FrameQuestionario extends javax.swing.JFrame
{
    private Questionario q;
    private int pos = 50;
    /**
     * Creates new form FrameQuestionario
     */
    public FrameQuestionario()
    {
        this.q = new Questionario();
        txtTitulo.setText(q.getTitulo());
        txtDesc.setText(q.getDescricao());
        initComponents();
    }

    FrameQuestionario(Questionario q)
    {
        this.q = q;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnAdddQuestao = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        txtDesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdddQuestao.setText("Adicionar questão");
        btnAdddQuestao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAdddQuestaoActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtTitulo.setText("Questionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdddQuestao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdddQuestao)
                    .addComponent(txtTitulo))
                .addGap(2, 2, 2)
                .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdddQuestaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAdddQuestaoActionPerformed
    {//GEN-HEADEREND:event_btnAdddQuestaoActionPerformed
        FrameOpcaoQuestao obj = new FrameOpcaoQuestao();
        obj.setVisible(true);
    }//GEN-LAST:event_btnAdddQuestaoActionPerformed
    
    public void exportarQuestao(Lista l)
    {   
        //txtEnun.setText(l.getEnunciado());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrameQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrameQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrameQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrameQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrameQuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdddQuestao;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}

//package geradordeformulario;
//
//import formulario.Lista;
//import formulario.Questionario;
//
//public class Principal
//{
//    public static void main(String[] args)
//    {
//        Questionario q;
//        q = new Questionario();
//        
//        Lista l = q.CriarQuestaoLista("Qual a sua cidade?");
//        
//        q.InsereItemLista(l, 'a', "Ceilândia");
//        q.InsereItemLista(l, 'b', "Taguatinga");
//        q.InsereItemLista(l, 'c', "Gama");
//        
//        q.ImprimeLista(l);
//        q.SalvaLista(l);
//        
//    }
//}
